substitutions:
  _REGION: europe-west1
  _SERVICE: marketing-ai-assistant
  _REPO: app-images         # Artifact Registry repo name (create once)
  _IMAGE: marketing-ai-assistant

steps:
# Build container
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA
    - -f
    - infra/cloudrun.Dockerfile
    - .

# Push image
- name: gcr.io/cloud-builders/docker
  args: ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA"]

# Deploy to Cloud Run
- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  entrypoint: gcloud
  args:
    - run
    - deploy
    - ${_SERVICE}
    - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA
    - --region=${_REGION}
    - --platform=managed
    - --allow-unauthenticated
    - --service-account=rtcrm-runtime@${PROJECT_ID}.iam.gserviceaccount.com

images:
- ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA
